"""add unit to medicine

Revision ID: f0c7a791ebe4
Revises: 1c8e05397b51
Create Date: 2026-07-23 10:54:03.757203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c7a791ebe4'
down_revision: Union[str, Sequence[str], None] = '1c8e05397b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('unit', sa.String(length=20), server_default='units', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine', 'unit')
    # ### end Alembic commands ###
